title: "Mario Paulin Vega"
email: "mpaulinv@gmail.com"
description: >-
  Personal website and portfolio of Mario Paulin Vega. 
  Showcasing projects, CV, and contact information.

baseurl: "" # Leave blank for user.github.io
url: "https://mpaulinv.github.io"

# Minimal Mistakes settings
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "mint" # Light, professional

# Social
author:
  name: "Mario Paulin Vega"
  avatar: "/assets/images/profile.jpg"
  bio: "Data Science Manager | Economics | Machine Learning"
  location: "Your City, Country"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/mpaulinv"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/mario-paulin-vega/"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:mpaulinv@gmail.com"

# Include pages folder - THIS IS THE KEY FIX
include:
  - _pages

# Collections for projects
collections:
  projects:
    output: true
    permalink: /projects/:path/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Defaults - Updated to include pages
defaults:
  # Projects
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "single"
      author_profile: true
  # Pages (including CV)
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "single"
      author_profile: true

# Build settings for GitHub Pages
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Google Analytics (optional)
google_analytics: ""
